In [8]:
import pandas as pd

summary_df = pd.read_csv("C:\\Users\\user\\OneDrive\\Desktop\\noise_collapse_project\\results\\2026-06-25_full_benchmark_with_train_predictions\\precollapse_entropy\\precollapse_entropy_summary.csv")

summary_df.head()

,series,model,mean_delta_shannon_entropy,mean_delta_permutation_entropy,final_delta_shannon_entropy,final_delta_permutation_entropy,mean_true_shannon_entropy,mean_pred_shannon_entropy,mean_true_permutation_entropy,mean_pred_permutation_entropy,collapse_index,train_test_index,collapse_status
0,linear_gaussian,ar1,0.061219,0.002014,0.000763,0.000807,0.926782,0.868753,0.847202,0.847963,3504,3504,confirmed
1,linear_gaussian,causal_encoder_transformer,0.010560,0.028079,0.027859,0.010905,0.926782,0.928808,0.847202,0.819122,3504,3504,confirmed
2,linear_gaussian,drift_naive,0.000704,0.000596,0.000116,0.000587,0.934014,0.933657,0.863805,0.863835,4500,3504,confirmed
3,linear_gaussian,gru_level,0.007172,0.070997,0.009778,0.058298,0.926782,0.927536,0.847202,0.776204,3504,3504,confirmed
4,linear_gaussian,lstm_increment,0.000740,0.000615,0.000116,0.000587,0.934014,0.933591,0.863805,0.863854,4500,3504,confirmed

In [9]:
summary_df.shape

(52, 13)

In [10]:
(summary_df["collapse_index"] >= summary_df["train_test_index"]).all()

True

In [11]:
import pandas as pd

segments_df = pd.read_csv("C:\\Users\\user\\OneDrive\\Desktop\\noise_collapse_project\\results\\2026-06-25_full_benchmark_with_train_predictions\\precollapse_entropy\\precollapse_entropy_by_segment.csv")

segments_df.head()

,series,model,segment,progress_start,progress_end,progress_mid,start_index,end_index,n_samples,split_status,train_test_index,collapse_index,collapse_status,true_shannon_entropy,pred_shannon_entropy,delta_shannon_entropy,true_permutation_entropy,pred_permutation_entropy,delta_permutation_entropy
0,linear_gaussian,ar1,1,0.0,0.1,0.05,16,364,349,train,3504,3504,confirmed,0.999736,0.411114,0.588623,-0.000000,0.011041,0.011041
1,linear_gaussian,ar1,2,0.1,0.2,0.15,364,713,350,train,3504,3504,confirmed,0.894685,0.893369,0.001316,0.816277,0.813392,0.002886
2,linear_gaussian,ar1,3,0.2,0.3,0.25,713,1062,350,train,3504,3504,confirmed,0.946088,0.955307,0.009218,0.943068,0.942700,0.000368
3,linear_gaussian,ar1,4,0.3,0.4,0.35,1062,1411,350,train,3504,3504,confirmed,0.922399,0.922228,0.000171,0.951422,0.952707,0.001285
4,linear_gaussian,ar1,5,0.4,0.5,0.45,1411,1760,350,train,3504,3504,confirmed,0.938368,0.938854,0.000486,0.967337,0.967700,0.000363

In [12]:
segments_df.shape

(520, 19)

In [13]:
segments_df["split_status"].value_counts()

split_status
train    448
mixed     52
test      20
Name: count, dtype: int64